name: Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      with:
        version: 13.x
    
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: test/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Install dependencies
      run: npm install
    
    - name: Run tests
      run: npm test
      continue-on-error: true
        
    - name: Upload report
      uses: actions/upload-artifact@v1
      with:
        name: Report
        path: report.html
